config:
    host: localhost
    port: 1111
project:
    name: pavilion-api-service
    version: 1.0.0
server:
    port: 8080
spring:
    cloud:
        config:
            profile: dev
            uri: http://${config.host}:${config.port}
            name: pavilion-config-service
    application:
        name: pavilion-api-service
    profiles:
        include: swagger
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    http:
        multipart:
            enabled: true
            file-size-threshold: 0
            location: D:/test
            max-file-size: 1MB
            max-request-size: 10MB
    # redis
    redis:
        database: 0
        host: r-2zeadd9a9ff39af4.redis.rds.aliyuncs.com
        password: pavilion@2018
        port: 6379
        timeout: 3000
        # redis线程池设置
        pool:
            max-idle: 50
            min-idle: 20
            max-active: 200
            max-wait: 3000
# druid配置
druid:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/pavilion?useUnicode=true&characterEncoding=utf8&useSSL=false
#    url: jdbc:mysql://localhost:3306/db_citizens_pavilion_v2?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://rm-2ze23u8did0t5re1jo.mysql.rds.aliyuncs.com:3306/db_citizens_pavilion_v2?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: pavilion
    password: pavilion@2018
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
# eureka
eureka:
    client:
        service-url:
            defaultZone: http://${eureka.host:localhost}:${eureka.port:8888}/eureka/
logging:
    level:
        tk:
            mybatis: TRACE
        com:
            framework: TRACE
    file: ${project.name}-${project.version}.log
    path: logs
pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count, countSql
mybatis:
    type-aliases-package: com.potevio.xacp.api.*.model, com.potevio.xacp.api.*.bean
    mapper-locations: classpath:mappers/*/*.xml
    configuration:
        map-underscore-to-camel-case: true
mapper:
    mappers: com.potevio.xacp.api.common.utils.MyMapper
    not-empty: true
    identity: MYSQL
